# Execute your favorite apps at launch
exec-once = swaync
exec-once = ashell 
exec-once = hyprpaper
exec-once = hypridle
source = ~/.config/hypr/local/autostart.conf
# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh
